name: CI
on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: action/setup-java@v2
        with:
          java-version: 19
          distribution: 'adopt'
        - name: Build with Gradle
          run: ./gradlew build