name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-gradle-project:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'adopt'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build --scan --no-daemon
        # hej