name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-with-upload-artifact:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: 'adopt'
            cache: gradle
        - name: Build with Gradle
          run: ./gradlew build --scan --no-daemon
        - name: Archive test report
          uses: actions/upload-artifact@v2
          with:
            name: Test report
            path: build/reports/tests/test