name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-with-gradle-build-action-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v3
        with:
          arguments: build --scan